CFLAGS=-pthread

all: part1-philosophers part3-philosophers part4-philosophers part5-reader-writer

part1-philosophers: part1-philosophers.c
	gcc ${CFLAGS} -o $@ $<

part3-philosophers: part3-philosophers.c
	gcc ${CFLAGS} -o $@ $<

part4-philosophers: part4-philosophers.c
	gcc ${CFLAGS} -o $@ $<

part5-reader-writer: part5-reader-writer.c
	gcc ${CFLAGS} -o $@ $<